services:
  - type: web
    name: python-rag-document-chat
    env: python
    runtime: python
    pythonVersion: "3.11"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
